# Generated by Django 5.0.1 on 2024-02-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=8192)),
                ('fatherCardId', models.CharField(max_length=333)),
                ('lastCardId', models.CharField(max_length=333)),
                ('sonCardId', models.CharField(max_length=333)),
                ('nextCardId', models.CharField(max_length=333)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('revisedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=20)),
                ('fatherTagId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CardTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.tags')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(to='card.tags'),
        ),
    ]
