# Generated by Django 5.0.1 on 2024-02-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='fatherCardId',
            field=models.CharField(max_length=333, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='lastCardId',
            field=models.CharField(max_length=333, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='nextCardId',
            field=models.CharField(max_length=333, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='sonCardId',
            field=models.CharField(max_length=333, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(null=True, to='card.tags'),
        ),
    ]
