# Generated by Django 5.0.1 on 2024-02-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_fathercardid_alter_card_lastcardid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='nextCardId',
        ),
        migrations.RemoveField(
            model_name='card',
            name='sonCardId',
        ),
        migrations.AlterField(
            model_name='card',
            name='fatherCardId',
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='lastCardId',
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='card.tags'),
        ),
    ]
