# Generated by Django 5.0.1 on 2024-02-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_remove_card_nextcardid_remove_card_soncardid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tagname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
